# 8장 : 지리정보 분석 및 시각화 (Folium)

In [1]:
# ! pip  install folium

Collecting folium
  Downloading folium-0.19.6-py2.py3-none-any.whl.metadata (4.1 kB)
Collecting branca>=0.6.0 (from folium)
  Downloading branca-0.8.1-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: jinja2>=2.9 in c:\users\admin\anaconda3\lib\site-packages (from folium) (3.1.4)
Requirement already satisfied: numpy in c:\users\admin\anaconda3\lib\site-packages (from folium) (1.26.4)
Requirement already satisfied: requests in c:\users\admin\anaconda3\lib\site-packages (from folium) (2.32.3)
Requirement already satisfied: xyzservices in c:\users\admin\anaconda3\lib\site-packages (from folium) (2022.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\admin\anaconda3\lib\site-packages (from jinja2>=2.9->folium) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\admin\anaconda3\lib\site-packages (from requests->folium) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from requests->folium) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\anaconda3\lib\site-packages (from requests->folium) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\anaconda3\lib\site-packages (from requests->folium) (2025.1.31)
Downloading folium-0.19.6-py2.py3-none-any.whl (112 kB)
Downloading branca-0.8.1-py3-none-any.whl (26 kB)
Installing collected packages: branca, folium
Successfully installed branca-0.8.1 folium-0.19.6

In [2]:
import folium
import pandas as pd
import numpy as np

In [26]:
# 우리집 위도 경도
lat = 35.17898806640068
lon = 129.0788299529799
m = folium.Map(location=[lat, lon],zoom_start=16)
m.save('data8/map.html')
m

In [49]:
# 서울시청 마크 찍기
lat = 37.56672955126769
lon = 126.97839477762068
m = folium.Map(location=[lat, lon],tiles='OpenStreetMap', zoom_start=17)
folium.Marker([lat, lon], popup='서울시청', icon=folium.Icon(color='red')).add_to(m)
folium.Marker([37.565562069676915, 126.97489758530945], popup='덕수궁', icon=folium.Icon(color='blue')).add_to(m)
m

In [61]:
tooltip = '클릭하세요.'
tooltips = [[37.5678264, 126.9776579], [37.565826456, 126.9796579]]
lat = 37.56672955126769
lon = 126.97839477762068
popups =['aa', 'bb']
latlngs = [[37.5678264, 126.9776579], [37.565826456, 126.9796579]]
m = folium.Map(location=[lat, lon],tiles='OpenStreetMap', zoom_start=15)
folium.Marker([lat, lon], popup='서울시청', tooltip=tooltip).add_to(m)
for i in range(len(latlngs)):
    folium.Marker([latlngs[i][0], latlngs[i][1]], 
                  popup=popups[i], tooltip=f'{tooltips[i][0]}, {tooltips[i][1]}').add_to(m)
m

In [64]:
m = folium.Map(location=[lat, lon],tiles='OpenStreetMap', zoom_start=15)
folium.Marker([lat, lon], popup='서울시청', tooltip=tooltip, icon=folium.Icon(color='red', icon='home')).add_to(m)
folium.Marker([37.5658859, 126.9754788], popup='덕수궁').add_to(m)
folium.CircleMarker([37.5658859, 126.9754788], popup='덕수궁', radius=100, color='#3186cc', fill=True, fill_color='#8631cc', fill_opacity=0.5).add_to(m)              
m

In [65]:
help(folium.Icon)

Help on class Icon in module folium.map:

class Icon(branca.element.MacroElement)
 |  Icon(color: str = 'blue', icon_color: str = 'white', icon: str = 'info-sign', angle: int = 0, prefix: str = 'glyphicon', **kwargs: Union[str, float, bool, Sequence, dict, NoneType])
 |
 |  Creates an Icon object that will be rendered
 |  using Leaflet.awesome-markers.
 |
 |  Parameters
 |  ----------
 |  color : str, default 'blue'
 |      The color of the marker. You can use:
 |
 |          ['red', 'blue', 'green', 'purple', 'orange', 'darkred',
 |           'lightred', 'beige', 'darkblue', 'darkgreen', 'cadetblue',
 |           'darkpurple', 'white', 'pink', 'lightblue', 'lightgreen',
 |           'gray', 'black', 'lightgray']
 |
 |  icon_color : str, default 'white'
 |      The color of the drawing on the marker. You can use colors above,
 |      or an html color code.
 |  icon : str, default 'info-sign'
 |      The name of the marker sign.
 |      See Font-Awesome website to choose yours.
 |      Warning : depending on the icon you choose you may need to adapt
 |      the `prefix` as well.
 |  angle : int, default 0
 |      The icon will be rotated by this amount of degrees.
 |  prefix : str, default 'glyphicon'
 |      The prefix states the source of the icon. 'fa' for font-awesome or
 |      'glyphicon' for bootstrap 3.
 |
 |  https://github.com/lvoogdt/Leaflet.awesome-markers
 |
 |  Method resolution order:
 |      Icon
 |      branca.element.MacroElement
 |      branca.element.Element
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, color: str = 'blue', icon_color: str = 'white', icon: str = 'info-sign', angle: int = 0, prefix: str = 'glyphicon', **kwargs: Union[str, float, bool, Sequence, dict, NoneType])
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __annotations__ = {}
 |
 |  color_options = {'beige', 'black', 'blue', 'cadetblue', 'darkblue', 'd...
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from branca.element.MacroElement:
 |
 |  render(self, **kwargs)
 |      Renders the HTML representation of the element.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from branca.element.Element:
 |
 |  __getstate__(self) -> dict
 |      Modify object state when pickling the object.
 |
 |      jinja2 Templates cannot be pickled, so remove the instance attribute
 |      if it exists. It will be added back when unpickling (see __setstate__).
 |
 |  __setstate__(self, state: dict)
 |      Re-add _template instance attribute when unpickling
 |
 |  add_child(self, child: 'Element', name: Optional[str] = None, index: Optional[int] = None) -> 'Element'
 |      Add a child.
 |
 |  add_children(self, child: 'Element', name: Optional[str] = None, index: Optional[int] = None) -> 'Element'
 |      Add a child.
 |
 |  add_to(self, parent: 'Element', name: Optional[str] = None, index: Optional[int] = None) -> 'Element'
 |      Add element to a parent.
 |
 |  get_bounds(self) -> List[List[Optional[float]]]
 |      Computes the bounds of the object and all it's children
 |      in the form [[lat_min, lon_min], [lat_max, lon_max]].
 |
 |  get_name(self) -> str
 |      Returns a string representation of the object.
 |      This string has to be unique and to be a python and
 |      javascript-compatible
 |      variable name.
 |
 |  get_root(self) -> 'Element'
 |      Returns the root of the elements tree.
 |
 |  save(self, outfile: Union[str, bytes, pathlib.Path, BinaryIO], close_file: bool = True, **kwargs)
 |      Saves an Element into a file.
 |
 |      Parameters
 |      ----------
 |      outfile : str or file object
 |          The file (or filename) where you want to output the html.
 |      close_file : bool, default True
 |          Whether the file has to be closed after write.
 |
 |  to_dict(self, depth: int = -1, ordered: bool = True, **kwargs) -> Union[dict, collections.OrderedDict]
 |      Returns a dict representation of the object.
 |
 |  to_json(self, depth: int = -1, **kwargs) -> str
 |      Returns a JSON representation of the object.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from branca.element.Element:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object

In [76]:
N=100
latitudes = np.random.uniform(low=35, high=39, size=N)
longitudes = np.random.uniform(low=125, high=129, size=N)

# (N, 2) 형태로 결합
data = np.column_stack((latitudes, longitudes))
popups = [str(i) for i in range(N)]
print(data)

[[ 37.77050793 126.49217762]
 [ 36.87623961 128.27002043]
 [ 37.39600701 128.71472345]
 [ 36.74686389 126.69582624]
 [ 38.23243671 126.84036924]
 [ 38.98574421 128.16821699]
 [ 38.91849288 125.54972153]
 [ 38.44353399 126.85605453]
 [ 38.14885988 125.65712779]
 [ 36.95860816 126.71282737]
 [ 36.3103785  126.57939079]
 [ 36.18393913 127.7509867 ]
 [ 38.18091088 126.34547386]
 [ 36.51037015 127.07141174]
 [ 37.36722179 128.25032511]
 [ 37.50962329 128.97249807]
 [ 36.25869984 128.56181409]
 [ 35.34197778 126.99050379]
 [ 36.19940313 127.80582223]
 [ 37.32547377 126.62118164]
 [ 36.6169634  125.07045962]
 [ 35.59502549 125.65517915]
 [ 36.55801273 125.23398592]
 [ 37.1468372  126.13900001]
 [ 37.8018353  128.10452455]
 [ 38.51311292 127.01795944]
 [ 35.76382054 126.90099295]
 [ 38.47170089 127.30955287]
 [ 38.80977553 125.20564199]
 [ 36.43889106 126.91662169]
 [ 38.09013055 125.53162997]
 [ 37.14915013 128.91813552]
 [ 35.54893761 127.8048086 ]
 [ 37.85699724 126.0232962 ]
 [ 36.60141367 127.50959954]
 [ 38.99246341 125.33686177]
 [ 36.63831091 127.72123093]
 [ 37.69770862 128.96785096]
 [ 36.04129297 125.90066953]
 [ 35.58122257 125.17029412]
 [ 38.73414499 126.61100465]
 [ 38.06639633 125.30060884]
 [ 35.25411456 125.45065086]
 [ 36.08163621 127.10173786]
 [ 36.13837755 128.66962816]
 [ 37.95013928 125.78344357]
 [ 36.59371425 125.94558656]
 [ 36.76281134 126.79974707]
 [ 35.94012057 127.12330956]
 [ 38.25415607 127.42878508]
 [ 36.65737313 125.63835348]
 [ 35.03461431 127.64923651]
 [ 38.31599409 125.16372615]
 [ 35.65865172 128.76396078]
 [ 38.2029798  125.44407317]
 [ 37.87608122 127.33471439]
 [ 36.173939   126.11448998]
 [ 38.86235219 125.75232541]
 [ 35.23660771 127.60559365]
 [ 38.23399653 126.7580391 ]
 [ 36.83604949 128.26332288]
 [ 36.53842741 127.33446653]
 [ 36.90388053 128.9757147 ]
 [ 35.47065384 128.89057609]
 [ 35.85305364 126.03880407]
 [ 36.9300064  125.88651743]
 [ 37.61622179 128.51024738]
 [ 38.63516234 128.56560244]
 [ 38.7084555  128.08780465]
 [ 35.90387681 125.9229284 ]
 [ 35.92201125 128.21954338]
 [ 35.40534338 127.77587715]
 [ 35.26607133 126.11369679]
 [ 37.45926648 127.23572813]
 [ 37.32140459 125.8646463 ]
 [ 35.97814841 128.60968591]
 [ 37.06119061 127.8659377 ]
 [ 37.86532879 128.98276321]
 [ 36.71286907 127.90354395]
 [ 38.26158743 128.85408417]
 [ 38.74351845 126.16910066]
 [ 36.16565845 125.30356629]
 [ 37.29726772 127.17357832]
 [ 37.53290936 125.13220342]
 [ 36.92854289 127.5035466 ]
 [ 38.10185152 125.83731559]
 [ 38.69296579 128.64919653]
 [ 37.03622056 125.20010743]
 [ 35.21041883 126.5508392 ]
 [ 37.84977927 127.51170682]
 [ 36.21130302 127.00635052]
 [ 36.12356843 126.34740312]
 [ 36.3467404  126.85666374]
 [ 35.00664985 127.27024245]
 [ 36.21384811 127.59579811]
 [ 36.34190069 128.44914518]
 [ 36.31503987 127.15479557]
 [ 36.75347611 127.23244652]
 [ 37.98004987 128.65934071]
 [ 36.83632254 126.89068324]]

In [74]:
m = folium.Map(location=[lat, lon], zoom_start=15)
for i in range(N):
    folium.Marker([data[i][0], data[i][1]], 
                  popup=f'위도: {data[i][0]}, 경도: {data[i][1]}',
                  icon=folium.Icon(color='green', icon='info-sign'),
                  tooltip=f'{data[i][0]}, {data[i][1]}').add_to(m)
m

In [77]:
from folium import plugins
m = folium.Map(location=[lat, lon], zoom_start=10)
plugins.MarkerCluster(data, popups=popups).add_to(m)
m

In [81]:
# 부산진구 CCTV 설치 위치 마크 표시
df = pd.read_csv('data8/CCTV_20190917.csv')
df

,관리기관명,소재지도로명주소,소재지지번주소,설치목적구분,카메라대수,카메라화소수,촬영방면정보,보관일수,설치년월,관리기관전화번호,위도,경도,데이터기준일자
0,부산광역시 부산진구청,부산광역시 부산진구 성지로 116,부산광역시 부산진구 초읍동 178-6,어린이보호,1,200.0,360도 전방면,30.0,NaN,051-605-4647,35.180330,129.051626,2019-09-17
1,부산광역시 부산진구청,부산광역시 부산진구 안창로14번길 78,부산광역시 부산진구 범천동 1536,어린이보호,0,NaN,NaN,NaN,NaN,051-605-4647,35.146126,129.043400,2019-09-17
2,부산광역시 부산진구청,부산광역시 부산진구 백양대로260번길 16,부산광역시 부산진구 개금동 419-3,어린이보호,0,NaN,NaN,NaN,NaN,051-605-4647,35.156511,129.022270,2019-09-17
3,부산광역시 부산진구청,부산광역시 부산진구 양지로11번길 64,부산광역시 부산진구 양정동 345-2,어린이보호,1,200.0,360도 전방면,30.0,NaN,051-605-4647,35.171487,129.071727,2019-09-17
4,부산광역시 부산진구청,부산광역시 부산진구 국악로60번길 4,부산광역시 부산진구 초읍동 616-15,어린이보호,0,NaN,NaN,NaN,NaN,051-605-4647,35.174720,129.050461,2019-09-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,부산광역시 부산진구청,부산광역시 부산진구 진사로61번길 28-7,부산광역시 부산진구 개금동 630-5,어린이보호,1,200.0,360도 전방면,30.0,NaN,051-605-4647,35.145796,129.019467,2019-09-17
85,부산광역시 부산진구청,부산광역시 부산진구 복지로 71,부산광역시 부산진구 개금동 565-14,어린이보호,0,NaN,NaN,NaN,NaN,051-605-4647,35.147113,129.018426,2019-09-17
86,부산광역시 부산진구청,부산광역시 부산진구 성지로104번길 26,부산광역시 부산진구 초읍동 540,어린이보호,1,200.0,360도 전방면,30.0,NaN,051-605-4647,35.180253,129.054447,2019-09-17
87,부산광역시 부산진구청,부산광역시 부산진구 백양대로320번길 40,부산광역시 부산진구 개금동 446-14,어린이보호,1,200.0,360도 전방면,30.0,NaN,051-605-4647,35.156259,129.015978,2019-09-17
88,부산광역시 부산진구청,부산광역시 부산진구 백양순환로 70-11,부산광역시 부산진구 당감동 775-2,어린이보호,1,200.0,360도 전방면,30.0,NaN,051-605-4647,35.168584,129.037950,2019-09-17

In [82]:
df1 = df.loc[df['카메라대수']>=1, :]
df1

,관리기관명,소재지도로명주소,소재지지번주소,설치목적구분,카메라대수,카메라화소수,촬영방면정보,보관일수,설치년월,관리기관전화번호,위도,경도,데이터기준일자
0,부산광역시 부산진구청,부산광역시 부산진구 성지로 116,부산광역시 부산진구 초읍동 178-6,어린이보호,1,200.0,360도 전방면,30.0,NaN,051-605-4647,35.180330,129.051626,2019-09-17
3,부산광역시 부산진구청,부산광역시 부산진구 양지로11번길 64,부산광역시 부산진구 양정동 345-2,어린이보호,1,200.0,360도 전방면,30.0,NaN,051-605-4647,35.171487,129.071727,2019-09-17
8,부산광역시 부산진구청,부산광역시 부산진구 백양대로208번길 174,부산광역시 부산진구 개금동 1-6,어린이보호,2,200.0,360도 전방면,30.0,NaN,051-605-4647,35.163590,129.024465,2019-09-17
9,부산광역시 부산진구청,부산광역시 부산진구 개금본동로9번길 41,부산광역시 부산진구 개금동 237-1,어린이보호,1,200.0,360도 전방면,30.0,NaN,051-605-4647,35.157119,129.023569,2019-09-17
10,부산광역시 부산진구청,부산광역시 부산진구 당감서로 16,부산광역시 부산진구 당감동 818-220,어린이보호,1,200.0,360도 전방면,30.0,NaN,051-605-4647,35.162333,129.036620,2019-09-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,부산광역시 부산진구청,부산광역시 부산진구 전포대로255번길 38,부산광역시 부산진구 전포동 656-1,어린이보호,1,200.0,360도 전방면,30.0,NaN,051-605-4647,35.159460,129.063532,2019-09-17
84,부산광역시 부산진구청,부산광역시 부산진구 진사로61번길 28-7,부산광역시 부산진구 개금동 630-5,어린이보호,1,200.0,360도 전방면,30.0,NaN,051-605-4647,35.145796,129.019467,2019-09-17
86,부산광역시 부산진구청,부산광역시 부산진구 성지로104번길 26,부산광역시 부산진구 초읍동 540,어린이보호,1,200.0,360도 전방면,30.0,NaN,051-605-4647,35.180253,129.054447,2019-09-17
87,부산광역시 부산진구청,부산광역시 부산진구 백양대로320번길 40,부산광역시 부산진구 개금동 446-14,어린이보호,1,200.0,360도 전방면,30.0,NaN,051-605-4647,35.156259,129.015978,2019-09-17
88,부산광역시 부산진구청,부산광역시 부산진구 백양순환로 70-11,부산광역시 부산진구 당감동 775-2,어린이보호,1,200.0,360도 전방면,30.0,NaN,051-605-4647,35.168584,129.037950,2019-09-17

In [97]:
popups = df1['소재지도로명주소'].tolist()
popups

['부산광역시 부산진구 성지로 116',
 '부산광역시 부산진구 양지로11번길 64',
 '부산광역시 부산진구 백양대로208번길 174',
 '부산광역시 부산진구 개금본동로9번길 41',
 '부산광역시 부산진구 당감서로 16',
 '부산광역시 부산진구 백양관문로77번길 33',
 '부산광역시 부산진구 거제천로40번길 31',
 '부산광역시 부산진구 복지로 117-12',
 '부산광역시 부산진구 백양대로136번길 90',
 '부산광역시 부산진구 연수로11번길 34',
 '부산광역시 부산진구 백양대로136번길 37-9',
 '부산광역시 부산진구 동평로39번길 106',
 '부산광역시 부산진구 냉정로178번길 13',
 '부산광역시 부산진구 백양관문로 25-29',
 '부산광역시 부산진구 화지로 6',
 '부산광역시 부산진구 당감서로 120',
 '부산광역시 부산진구 복지로 70',
 '부산광역시 부산진구 백양순환로18번길 36',
 '부산광역시 부산진구 당감서로100번길 56',
 '부산광역시 부산진구 당감로64번길 27',
 '부산광역시 부산진구 경마장로5번길 71',
 '부산광역시 부산진구 엄광로 122',
 '부산광역시 부산진구 범천로 30',
 '부산광역시 부산진구 새싹로14번길 7',
 '부산광역시 부산진구 성지로46번길 15',
 '부산광역시 부산진구 시민공원로19번길 62',
 '부산광역시 부산진구 신암로 97',
 '부산광역시 부산진구 백양산로 23',
 '부산광역시 부산진구 백양대로136번길 90',
 '부산광역시 부산진구 양지로5번길 31',
 '부산광역시 부산진구 양지로17번길 28',
 '부산광역시 부산진구 동평로 350',
 '부산광역시 부산진구 백양대로300번길 30',
 '부산광역시 부산진구 냉정로 199',
 '부산광역시 부산진구 당감로 118',
 '부산광역시 부산진구 전포대로255번길 38',
 '부산광역시 부산진구 진사로61번길 28-7',
 '부산광역시 부산진구 엄광로 325',
 '부산광역시 부산진구 엄광로182번길 49',
 '부산광역시 부산진구 대학로 16-1',
 '부산광역시 부산진구 가야대로482번길 87',
 '부산광역시 부산진구 가야대로443번길 25-10',
 '부산광역시 부산진구 백양대로320번길 40',
 '부산광역시 부산진구 백양관문로77번길 17',
 '부산광역시 부산진구 백양대로208번길 9',
 '부산광역시 부산진구 개금본동로66번길 12-12',
 '부산광역시 부산진구 당감로 22-5',
 '부산광역시 부산진구 백양대로136번길 26',
 '부산광역시 부산진구 동성로 26',
 '부산광역시 부산진구 백양산로 99',
 '부산광역시 부산진구 백양산로 43',
 '부산광역시 부산진구 당감서로65번길 31',
 '부산광역시 부산진구 범천로 30',
 '부산광역시 부산진구 신천대로263번길 26',
 '부산광역시 부산진구 부전로65번길 25',
 '부산광역시 부산진구 엄광로 412',
 '부산광역시 부산진구 황령대로 79',
 '부산광역시 부산진구 중앙번영로 25',
 '부산광역시 부산진구 전포대로298번길 15',
 '부산광역시 부산진구 시민공원로 62',
 '부산광역시 부산진구 황령산로605번길 35-10',
 '부산광역시 부산진구 양성로 34',
 '부산광역시 부산진구 중앙대로941번길 24',
 '부산광역시 부산진구 연지로 29',
 '부산광역시 부산진구 초읍천로43번길 10',
 '부산광역시 부산진구 전포대로255번길 38',
 '부산광역시 부산진구 진사로61번길 28-7',
 '부산광역시 부산진구 성지로104번길 26',
 '부산광역시 부산진구 백양대로320번길 40',
 '부산광역시 부산진구 백양순환로 70-11']

In [98]:
# 중심 위도, 경도 계산
lat_avg = np.array(df1['위도'].tolist()).mean()
lng_avg = np.array(df1['경도'].tolist()).mean()
lat_avg, lng_avg
m = folium.Map(location=[lat_avg, lng_avg], zoom_start=15)

In [100]:
data = np.array([df1['위도'].tolist(), df1['경도'].tolist()]).T
for i in range(len(data)):
    folium.Marker([data[i][0], data[i][1]], 
                  popup=popups[i], 
                  icon=folium.Icon(color='red', icon='info-sign'),
                  tooltip=f'{data[i][0]}, {data[i][1]}').add_to(m)
m

In [101]:
m = folium.Map(location=[lat_avg, lng_avg], zoom_start=12)
plugins.MarkerCluster(data, popups=popups).add_to(m)
m.save('data8/cctv_map.html')
m